# Generated by Django 4.2.6 on 2023-10-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                ("format", models.CharField(max_length=56)),
                ("attachment", models.FileField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
