# Generated by Django 4.2.6 on 2023-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
