# Generated by Django 4.2.6 on 2023-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_alter_application_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("phone", models.CharField(max_length=26)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
