version: "3.9"

name: zetatech_deploy

services:
  zetatech_db:
    image: postgres:15.4-alpine
    container_name: zetatech_db
    restart: always
    networks:
      - production_network
    volumes:
      - "./backend/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - "zetatech_dev_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_PORT}
  
  zetattech_api:
    container_name: zetatech_api
    restart: always
    build: 
      context: ./../../..
      dockerfile: ./deployments/docker/service/ServerDockerfile
    networks: 
      - production_network
    volumes:
      - "../../zetatech/zetatech_backend/:/usr/service:rw"
      - "static_zetatech_service_production_volumes:/usr/service/staticfiles"
    depends_on:
      - zetatech_db
    command: gunicorn backend.zetatech_backend.core.wsqi -bind 0.0.0.0
    ports:
      - "${PORT}:8000"
    environment:
      - SERVICE_NAME=zetatech_api

  zetatech_redis:
    image: redis:latest
    container_name: zetatech_redis
    networks:
      - production_network
    restart: always
    expose:
      - 6379

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:1.25.2-alpine-slim"
    networks:
      - production_network
    volumes:
      - "../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../nginx/templates:/etc/nginx/templates:ro"
      - "static_zetatech_service_production_volumes:/usr/zetatech_service/staticfiles:rw"
      - "cerbot_www_volume_production_volumes:/var/www/certbot/:ro"
      - "cerbot_conf_volume_production_volumes:/etc/nginx/ssl/:ro"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${PROD_NGINX_HOST}
      - NGINX_PORT=80

      - ZETATECH_SERVICE_HOST=zetatech_service_api
      - ZETATECH_SERVICE_PORT=${PROD_ZETATECH_SERVICE_PORT}

      - WEB_HOST=web
      - WEB_PORT=${PROD_WEB_PORT}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - cerbot_www_volume_production_volumes:/var/www/certbot/:rw
      - cerbot_conf_volume_production_volumes:/etc/letsencrypt/:rw

volumes:
  static_zetatech_service_production_volumes:
  cerbot_www_volume_production_volumes:
  cerbot_conf_volume_production_volumes:
  zetatech_dev_postgres_data:

networks:
  production_network:
    name: production_network
