# Generated by Django 4.2.6 on 2023-10-27 18:37

import apps.team.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField()),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.team.models.get_image_path,
                        verbose_name="Картинка",
                    ),
                ),
            ],
        ),
    ]
