# Generated by Django 4.2.6 on 2023-10-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="position",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
