services:
  base:
    restart: always
    build:
      context: ./../../..
      dockerfile: deployments/docker/service/Dockerfile
    networks:
      - zetatech
    volumes:
      - "../../../backend/zetatech_backend/:/usr/service:rw"
      - "dev_static_files:/usr/service/staticfiles"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DOMAIN=${DOMAIN}

      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - DB_PORT=${DB_PORT}
      - DB_HOST=zetatech_db

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_TLS=${EMAIL_HOST_TLS}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST_PORT=${EMAIL_HOST_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}