# Generated by Django 4.2.6 on 2023-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user_id", "product_id"), name="user product"
            ),
        ),
    ]
