# Generated by Django 4.2.6 on 2023-11-08 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Избранное", "verbose_name_plural": "Избранное"},
        ),
    ]
