# Generated by Django 4.2.6 on 2023-11-20 20:45

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user/avatar/",
                verbose_name="Картинка",
            ),
        ),
    ]
