# Generated by Django 4.2.6 on 2023-10-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Автоматическое поле, можно заполнить вручную.",
                        max_length=80,
                        unique=True,
                        verbose_name="Слаг тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ("name",),
                "default_related_name": "post_tags",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=60, verbose_name="SEO заголовок"),
                ),
                ("h1", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "description",
                    models.CharField(
                        max_length=400, verbose_name="SEO описание публикации"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="media/", verbose_name="Изображение"
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст публикации")),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Автоматическое поле, можно заполнить вручную.",
                        max_length=180,
                        unique=True,
                        verbose_name="Слаг статьи",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="blog.tagpost", verbose_name="Теги"),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ("-created_at",),
                "default_related_name": "posts",
            },
        ),
    ]
